main changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,7 +39,8 @@ jobs:
           echo "Running file: ${{ matrix.testFile }}"  
 
       - name: Run test file
-        run: xvfb-run npx playwright test ${{ matrix.testFile }} --reporter=html || echo "failed" > status.txt if [ ! -f status.txt ]; then echo "passed" > status.txt; fi
+        run: xvfb-run npx playwright test ${{ matrix.testFile }} --reporter=html || echo "failed" > status.txt if [ ! -f status.txt ]; 
+             then echo "passed" > status.txt; fi
         working-directory: playwright_automation
         continue-on-error: true
 
