Test3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,8 +16,8 @@ jobs:
           name: Test1
         - testFile: playwright_automation/tests/home.spec.ts
           name: Test2
-        - testFile: playwright_automation/tests/login.spec.ts
-          name: Test3
+        # - testFile: playwright_automation/tests/login.spec.ts
+        #   name: Test3
 
     steps:
       - name: Checkout code
@@ -39,8 +39,17 @@ jobs:
           echo "Running file: ${{ matrix.testFile }}"  
 
       - name: Run test file
-        run: npx playwright test ${{ matrix.testFile }} --reporter=list,html,json
+        run: npx playwright test ${{ matrix.testFile }} --reporter=list,html,json,blob
         continue-on-error: true
+
+      - name: List workspace contents
+        run: |
+         echo "Current directory:"
+         pwd
+         echo "--- Top-level files/folders ---"
+         ls -la
+         echo "--- .report folder (if it exists) ---"
+         ls -R .report || echo ".report folder not found"
 
       - name: List report directory
         run: |
@@ -77,6 +86,16 @@ jobs:
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
+
+      - name: List merge directory
+        run: |
+          echo "Checking contents of workspace..."
+          ls -la 
+          # echo "--- playwright-report"
+          # ls -la playwright-report
+          # echo "--- test-results"
+         
+          # ls -la test-results || echo "test-results directory not found"  
 
       - name: Merge reports
         run: |
