test-results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,11 +46,11 @@ jobs:
         run: |
           echo "Checking contents of workspace..."
           ls -la 
-          echo "---"
-          ls -la playwright_automation
-          echo "---"
-          echo "---"
-          ls -la my-report || echo "my-report directory not found"  
+          echo "--- playwright-report"
+          ls -la playwright-report
+          echo "--- test-results"
+         
+          ls -la test-results || echo "test-results directory not found"  
 
       - name: Upload HTML report for ${{ matrix.name }}
         uses: actions/upload-artifact@v4
